### ISSUE TITLE
Menu, Copyright and links in footer

### ISSUE THREAD

**Issue by danieleguido** [C2DH/minett-stories#103]
- [x]  This is the sentence that needs to be added in the menubar (or preferably in a footer)
    > Copyright © [Université du Luxembourg](https://wwwen.uni.lu/) 2022. All rights reserved.
    The link below the C2DH logo should point to https://www.uni.lu
- [x] Add "menu" next to the menu icon :) 
- [ ] "menu" is not visible after the intro, in /stories

**Comment by giorgiouboldi** [comment]
![Screenshot 2022-05-20 at 10 51 48](https://user-images.githubusercontent.com/2106518/169491890-95048ed3-2583-4f24-9e6c-0b1ceb52cb8c.png)
