### ISSUE TITLE
Format education page as about

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#113]
Formattare la pagina come about. Al momento da 404

**Comment by skaffo** [comment]
@danieleguido

**Comment by danieleguido** [comment]
era con status "non pubblicato". Ora non è più 404 ma la struttura della pagina sembra diversa dalle altre, non c'è più h1 @skaffo ? 
<img width="359" alt="Screenshot 2022-05-23 at 08 32 19" src="https://user-images.githubusercontent.com/1181642/169757677-74f91547-18ae-46b6-a201-965ae6f49320.png">
<img width="359" alt="Screenshot 2022-05-23 at 08 32 41" src="https://user-images.githubusercontent.com/1181642/169757749-eb3ab6e3-b90c-4369-a688-16608392cbb3.png">

**Comment by skaffo** [comment]
@danieleguido pushato versione corretta.
