### ISSUE TITLE
Update logo ESCH

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#116]
sia in intro, che menu che about page
<img width="110" alt="logo-esch" src="https://user-images.githubusercontent.com/2106518/169343868-6cd93d7c-35fc-465d-8c0f-3efa3a8259c2.png">

**Comment by giorgiouboldi** [comment]
nel menu è ancora quello vecchio @skaffo

**Comment by skaffo** [comment]
@giorgiouboldi ok corretto.
