### ISSUE TITLE
Check graphic novels on Firefox

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#122]

**Comment by giorgiouboldi** [comment]
Sembra ci siano altri problemi con firefox+android o ipad: 

26. Android + firefox, on the landing page Remixing industrial pasts and the language buttons overlap.

27. Android + firefox, videos in interactive video stories do not load, video only works

28. Android + firefox, interactive maps do not load (something went wrong)

29. Ipad + firefox, images/text in graphic novel are sometimes clinched

**Comment by skaffo** [comment]
@giorgiouboldi io sto testando con Android 12 e Firefox non ho notato questi problemi. Si possono avere più info sul dispositivo usato?

**Comment by skaffo** [comment]
@giorgiouboldi ok il problema su firefox.
