### ISSUE TITLE
Audio story e Video Story Subtitles

### ISSUE THREAD

**Issue by skaffo** [C2DH/minett-stories#123]
Aggiungere sottotitoli.

**Comment by giorgiouboldi** [comment]
cambia lo stile (grandezza, allineamento e bordo) per migliorare la leggibilità

https://www.figma.com/file/ieZfBmF2ZE4awu8aDWuTLT/Remixing-Pasts-Design?node-id=232%3A10335

**Comment by skaffo** [comment]
@giorgiouboldi cambiato style.
