### ISSUE TITLE
Problemi Firefox + Android

### ISSUE THREAD

**Issue by skaffo** [C2DH/minett-stories#124]
Android + firefox, on the landing page Remixing industrial pasts and the language buttons overlap.

Android + firefox, videos in interactive video stories do not load, video only works

Android + firefox, interactive maps do not load (something went wrong)

Ipad + firefox, images/text in graphic novel are sometimes clinched

**Comment by giorgiouboldi** [comment]
Un altro problema con Firefox. 
In questo graphic novel - e non negli altri - c'è uno spazio fra l'ultima immagine e "next chapter"
https://minett-stories.lu/en/story/history-of-air-pollution/explore

**Comment by skaffo** [comment]
@giorgiouboldi questo ultimo problema fixato.
