### ISSUE TITLE
Graphic novel object with caption 

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#129]
Lo vedo così su Iphone SE with Chrome ma con ispeziona elemento si vede normale.
![IMG_1214](https://user-images.githubusercontent.com/2106518/170223598-5b562ae4-a25f-4111-9f8a-8dc08599b9b9.PNG)

**Comment by gffuma** [comment]
@giorgiouboldi Safari?

**Comment by giorgiouboldi** [comment]
Si scusa, safari.

**Comment by gffuma** [comment]
Proviamo a darci un occhio ma anche su Desktop sembra che safari se non ha le immagini già in cache a volte completamente random le disegna con la larghezza sbagliata, quindi è anche difficile riprodurre il problema in quanto appunto capita random, proviamo comunque a vedere cosa si può fare per mitigare il problema.

**Comment by gffuma** [comment]
Dovrebbe andare un po' meglio su safari quando [a63f1da](https://github.com/C2DH/minett-stories/commit/a63f1da530abc98c490d5afd391c67a222372394) andrà online.
