### ISSUE TITLE
Subtitles in video stories are overlapping with the player

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#136]
I sottotitoli sono da sistemare che ora vanno sul player
https://minett-stories.lu/en/story/crimes-and-subsistence/explore

![Screenshot 2022-05-27 at 12 28 58](https://user-images.githubusercontent.com/2106518/170682774-5cb83e82-a389-40a0-8e7f-9e98360dd307.png)

**Comment by skaffo** [comment]
@giorgiouboldi fixato.
