### ISSUE TITLE
Miller API Documents can't exclude multiple filters

### ISSUE THREAD

**Issue by gffuma** [C2DH/minett-stories#27]
Can't exclude multiple filters using Miller API related to #16 

This works:
`https://minett-stories.lu/api/document/?exclude={ "type": "entity" }`

This also works:
`https://minett-stories.lu/api/document/?exclude={ "data__type": "drawing" }`

This doesn't work:
`https://minett-stories.lu/api/document/?exclude={ "type": "entity", "data__type": "drawing" }`

**Comment by danieleguido** [comment]
on it :)

**Comment by danieleguido** [comment]
@gffuma the field s in the `exclude`params are concatenated with an `AND` operator, I guess you need an OR operator in between, am I correct?

**Comment by danieleguido** [comment]
I've managed to add a `where` params that allows you to concatenate complex filters. See  [miller 1b169d6](https://github.com/C2DH/miller/commit/1b169d6010ad2356778fdcb428177aa16198f6d7)
```
https://minett-stories.lu/api/document/?where={"Op.not":[{"Op.or":[{"type":"entity"},{"data__type":"drawing"}]}]}
```

```json
{
  "Op.not": [
    {
      "Op.or": [
        {"type": "entity"},
        {"data__type": "drawing"}
      ]
    }
  ]
}
```
resulting in Q filter: `(NOT (AND: (OR: ('type', 'entity'), ('data__type', 'drawing'))))`
