### ISSUE TITLE
Miller API Unsafe charters in slug

### ISSUE THREAD

**Issue by gffuma** [C2DH/minett-stories#29]
We use slug to generate beautiful documents link but some documents contains slugs with unsafe charters.
Es:.
[https://minett-stories.lu/api/document/52/](https://minett-stories.lu/api/document/52/)

**Comment by danieleguido** [comment]
We didn’t put in place any automatic cleaning not to have unexpected results (e.g. to avoid duplicates) and as long as the `slug` is a valid string is being accepted... 
However, you're right, the strings containing other characters than English `a-z` won’t work correctly in our browsers.
I've asked our user not to use umlaut or special characters like parenthesis, but I will correct them manually :( 
As there's no strict convention, I would transliterate all weird slugs from `ICH MÖGEN KEIN NUDEL (maybe)` to something like : `ich-moegen-kein-nudel--maybe`

**Comment by gffuma** [comment]
Is an option to using something like this https://docs.djangoproject.com/en/4.0/ref/utils/#django.utils.text.slugify during import can guarantee the slug to be safe? And if the slug exists appends something like a count 2,3 ecc or a tiny unique piece with a hash library for example https://pypi.org/project/nanoid/

**Comment by danieleguido** [comment]
it is like this if we use django directly, see https://github.com/C2DH/miller/blob/miller-v2/miller/models/document.py#L124  
The import method we use is quite special, as we assume the JSON we get from the googe spreadhseet is somehow "clean" 👼  ...

**Comment by danieleguido** [comment]
also, automatic slug could determine a misalignment between the data we have in the db and the spreadsheet

**Comment by danieleguido** [comment]
Closing for now as I'm going to fix each document slug manually 💣
