### ISSUE TITLE
Missing modules for graphic novel

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#31]
Here are the modules to be implemented:
- Text+object (the position of the image is given by the option within the module)
- Object with custom caption. The text appears below ONLY when a custom caption is added to the object module.

![modules](https://user-images.githubusercontent.com/2106518/164652465-c2e12112-6e74-4e0f-accb-face00bc541c.jpg)

**Comment by skaffo** [comment]
@giorgiouboldi there is an example in the database for test it?
