### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by gffuma** [C2DH/minett-stories#35]
Favicon?

**Comment by giorgiouboldi** [comment]
![favicon](https://user-images.githubusercontent.com/2106518/165304840-cb0d9fb1-aec8-4b11-ab1f-2f780a4d2789.png)

**Comment by skaffo** [comment]
@giorgiouboldi can you give me the image in these formats 192x192 e 512x512 for the manifest file of the project.

**Comment by giorgiouboldi** [comment]
![192](https://user-images.githubusercontent.com/2106518/165750042-9f3b9bc2-70e8-496d-b00a-45555eda00ee.png)
![512](https://user-images.githubusercontent.com/2106518/165750047-25106094-726f-4559-9829-17ad317b682c.png)
