### ISSUE TITLE
Miller Suggest API

### ISSUE THREAD

**Issue by gffuma** [C2DH/minett-stories#36]
I think the suggest API is missing: `api/document/suggest/?q={query}`

**Comment by danieleguido** [comment]
code for that method is obsolete, need to be refactored :(

**Comment by gffuma** [comment]
So we can definitely drop this feature (for me is ok 😄 )?

**Comment by danieleguido** [comment]
it's a question for @giorgiouboldi :)

**Comment by giorgiouboldi** [comment]
yes, we can drop it!
