### ISSUE TITLE
test subtitles

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#37]
Link to subtitles in srt:
https://minett-stories.lu/api/document/ch6-virtual-hike-0-main-video/

**Comment by gffuma** [comment]
Need `vtt` format for the web you can easy convert from `srt` with:
https://atelier.u-sub.net/srt2vtt/

**Comment by giorgiouboldi** [comment]
@danieleguido

**Comment by danieleguido** [comment]
hi @giorgiouboldi I've added the vtt for the available videos, please check the `ch6-virtual-hike-0-main-video` document
