### ISSUE TITLE
Add videos as documents in the "interactive video" module

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#45]
I can't pick "video" data types now. Can we do it like we did in the Post project?
https://175anspost.lu/stories/introduction-du-standard-gsm-au-luxembourg?lang=fr (See 19:30)

**Comment by skaffo** [comment]
@giorgiouboldi i don't understand the task can you explain me more?

**Comment by giorgiouboldi** [comment]
Intendo mettere dei video nei 2 rettangoli sotto. Ora posso solo mettere immagini. Nel progetto Post175 si potevano allegare dei video che partono in automatico

**Comment by gffuma** [comment]
At the moment we can't select a video as document in the video interview module can we have an example of working story with a related video?

**Comment by giorgiouboldi** [comment]
can you allow the selection of videos @danieleguido ?

**Comment by danieleguido** [comment]
And done in this patch of the visual editor https://github.com/C2DH/visual-editor/pull/44 (it is already published online as a preview), please reopen if needed :)
