### ISSUE TITLE
Thumbnails voronoi

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#46]
Is it possible to to use the cropped image for the voronoi? Otherwise is it possible to improve how the image fit the voronoi cells (see example)?

![Screenshot 2022-04-28 at 14 31 33](https://user-images.githubusercontent.com/2106518/165752492-a72b5988-ff23-4c0f-b719-237ea5d43b17.png)

**Comment by skaffo** [comment]
@giorgiouboldi ho pushato online una prova.

**Comment by giorgiouboldi** [comment]
Ma il crop funziona? ci sono dei limiti di dimensione per caso?
Alcune croppate come vedi non vengono visualizzate
![Screenshot 2022-05-03 at 14 46 43](https://user-images.githubusercontent.com/2106518/166455490-50ca9ef9-60f6-478a-a5fa-6221e23f5016.png)

**Comment by giorgiouboldi** [comment]
see also https://github.com/C2DH/minett-stories/issues/75

**Comment by gffuma** [comment]
After a lot research i think is quite impossible cropping the image in the browser and use ti to fill the voronoi area.
I also do some research on previous works for example the ww1 exhibition site and i found an interesting thing.
In the ww1 version for example bbox isn't compute on the client but rather there was an api on Miller to do that and there is the motivation that now on editor wont work.

See:
https://github.com/C2DH/visual-editor/blob/2f259ab6c783f6a156eb063e4c298b993897b04c/src/utils/index.js#L136

Also look at in the frontend:
https://github.com/C2DH/ww1/blob/1b91b67f26998ede2ccc00ce28e3bcb275fc8d89/src/utils.js#L133

Also in the production site:

<img width="1437" alt="Schermata 2022-05-06 alle 16 27 48" src="https://user-images.githubusercontent.com/5680676/167154650-f7545bc3-e12b-478d-a9d6-d17adf1e8986.png">

The `_c[373,407,2332,1518]` of the image url is the selected bbox.

I think this api no longer exists cc @danieleguido 

Now we can adjust how images fill to avoid cut them but we can't implement precise bbox selection.

**Comment by giorgiouboldi** [comment]
ok, we should then upload pre-cropped images right?

**Comment by gffuma** [comment]
Yes, but i think we need a special field for this image, because we need also the cover for story landing page.

**Comment by gffuma** [comment]
@giorgiouboldi can be closed?

**Comment by giorgiouboldi** [comment]
SI!!! @skaffo
