### ISSUE TITLE
Can we add a breakpoint for very large screens?

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#54]
Would it possible to add a new breakpoint for laaaaarge screens? 
In this way we can control the width of the texts in the articles a bit better and have 4 col offset and 4 col with the content

**Comment by giorgiouboldi** [comment]
se si riesce farei un custom breakpoint

**Comment by gffuma** [comment]
A partire da quale width ?

**Comment by danieleguido** [comment]
Probably related to this: <img width="500" alt="Screenshot 2022-05-12 at 10 01 22" src="https://user-images.githubusercontent.com/1181642/168021718-b9ec19c2-133a-4d74-9e21-bbd1b1dc6198.png">
<img width="1636" alt="Screenshot 2022-05-12 at 10 01 40" src="https://user-images.githubusercontent.com/1181642/168021781-1fc22be8-26f6-46ed-bc14-5ae5d3203e3e.png">

**Comment by skaffo** [comment]
ciao @giorgiouboldi ci sto ancora lavorando. Unica cosa inserendo lo spazio e il bordo sopra l'H2 in questi schermi giganti i moduli testo + oggetto risultano a volte avere delle spaziature non bellissime da vedere.

**Comment by skaffo** [comment]
![9B2B3EDC-6BB4-4E9B-ADDD-00E30B8784E6](https://user-images.githubusercontent.com/16683586/168030824-b9653916-5413-47a1-a3ce-f145abfd38da.jpeg)
