### ISSUE TITLE
Document page - data.provenance is not correct

### ISSUE THREAD

**Issue by danieleguido** [C2DH/minett-stories#58]
It seems there's a duplicate field:
`https://minett-stories.lu/de/document/326`

The **provenance** should be: `Archives de la ville d’Esch`

![Screenshot 2022-05-04 at 14 05 36](https://user-images.githubusercontent.com/1181642/166677850-bff0fcc6-7cfa-4cf5-90c8-e17d2b8c5599.png)

**Comment by giorgiouboldi** [comment]
Can you check it @skaffo?

**Comment by skaffo** [comment]
@giorgiouboldi yes just checked and fixed. sorry.
