### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#71]

**Comment by skaffo** [comment]
@giorgiouboldi ho cambiato il loader ma sembra un po' sgranato.

**Comment by giorgiouboldi** [comment]
Prova questo @skaffo
![loader](https://user-images.githubusercontent.com/2106518/167440587-2c4d307e-1f24-46a9-9c1e-9d0a1810160d.gif)

**Comment by skaffo** [comment]
@giorgiouboldi caricato il nuovo loader.
