### ISSUE TITLE
Thumbnail for social media

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#72]

**Comment by giorgiouboldi** [comment]
Va bene così per la metatag come dimensione/proporzione @skaffo 
![social](https://user-images.githubusercontent.com/2106518/166725419-7c22dd28-cdb6-4fec-8369-a166159936a9.png)
?

**Comment by giorgiouboldi** [comment]
mi puoi dire dove si trova l'immagine nel repo così se devo cambiarla posso farlo io?

**Comment by gffuma** [comment]
Qui: https://github.com/C2DH/minett-stories/blob/master/src/assets/socialMediaImage.png
