### ISSUE TITLE
Text styles on mobile articles

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#74]
Per migliorare la leggibilità farei delle modifiche. 
Trovi dimensioni font e line height in questo frame di Figma:

https://www.figma.com/file/ieZfBmF2ZE4awu8aDWuTLT/Remixing-Pasts-Design?node-id=1608%3A9462

**Comment by giorgiouboldi** [comment]
ok ma quando accedo all'articolo da "go deeper" all'inizio o da dopo aver aperto la storia, i margini a lato sono diversi. Meglio adattarli alla prima immagine @skaffo 
![IMG_1160](https://user-images.githubusercontent.com/2106518/167425982-fe0cd17d-b09d-442e-9ff6-ef561bd562fd.PNG)
![IMG_1159](https://user-images.githubusercontent.com/2106518/167425991-ce98e32f-7bc6-4c11-8c15-f98680603179.PNG)

**Comment by skaffo** [comment]
@giorgiouboldi ok giorgio pushato la modifica.
