### ISSUE TITLE
Thumbnails on firefox are not visible

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#75]
![Screenshot 2022-05-05 at 11 39 03](https://user-images.githubusercontent.com/2106518/166898535-7c1a18cc-0b51-49b2-adf0-2c7f0a8be063.png)

**Comment by giorgiouboldi** [comment]
ora si vedono ma mi sembra un po' lento. Problema mio? @skaffo

**Comment by gffuma** [comment]
Deve ancora andare online questo https://github.com/C2DH/minett-stories/commit/ffe352376077980fd5509ddbc0746e4a3ae0fcfb
