### ISSUE TITLE
Graphic novels on mobile

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#79]
La barra sotto copre parte dell'immagine.
![IMG_1146](https://user-images.githubusercontent.com/2106518/166919598-43657473-02bd-4959-9b64-ab7ccad15892.PNG)

**Comment by skaffo** [comment]
@giorgiouboldi su che dispositivo giorgio non riesco a replicare il problema.

**Comment by giorgiouboldi** [comment]
iphone SE - browser chrome

**Comment by giorgiouboldi** [comment]
non so cosa è cambiato ma ora c'è pan orizzontale e verticale nei graphic novel su mobile

https://user-images.githubusercontent.com/2106518/167860779-e1146d3d-82f7-446d-9460-e466d0ad71c8.MP4
