### ISSUE TITLE
Update logos

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#86]
Da aggiornare in intro, menu e about page

[logos.zip](https://github.com/C2DH/minett-stories/files/8632581/logos.zip)

**Comment by skaffo** [comment]
@giorgiouboldi devono avere qualche link?

**Comment by giorgiouboldi** [comment]
Mi sembra che il secono logo abbia un'altezza un pochino diversa. Puoi metterlo alla stessa altezza dell'altro?

**Comment by skaffo** [comment]
@giorgiouboldi ok appena modificata altezza dei loghi al prossimo deploy trovi online.
