### ISSUE TITLE
link to next chapter in graphic novel

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#87]
Quando finisce un capitolo viene subito caricato il capitolo dopo? Se no potremmo mettere un link per caricare il secondo capitolo (vedi screenshot). Se è l'ultimo capitolo non mettiamo nulla. 
![Screenshot 2022-05-05 at 17 44 10](https://user-images.githubusercontent.com/2106518/166961449-c8d121cd-a8a2-40fb-910a-6f1b619db6cb.png)

**Comment by skaffo** [comment]
@giorgiouboldi non va in automatico al capitolo successivo posso inserire il box con che sfondo?

**Comment by giorgiouboldi** [comment]
ok sfondo 383838 (dark grey) e testo bianco in maiuscolo.
