### ISSUE TITLE
PDF previews are not displayed in stories

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#9]
PDFs are visible only in galleries but not in text+objet or object only modules.

**Comment by gffuma** [comment]
@giorgiouboldi Can show where it happens?

**Comment by gffuma** [comment]
https://minett-stories.lu/en/story/virtual-walk-in-the-haard/explore
I had a PDF as last item of long scroll and it works 🤔 maybe it's a problem with data?

**Comment by danieleguido** [comment]
On it :)

**Comment by danieleguido** [comment]
It looks ok from my side?

**Comment by skaffo** [comment]
@giorgiouboldi we can close?
