### ISSUE TITLE
dark background in titles under interactive maps

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#91]

**Comment by giorgiouboldi** [comment]
![Screenshot 2022-05-10 at 10 34 29](https://user-images.githubusercontent.com/2106518/167586810-f4e550ed-72a1-432b-85ae-8d47df447070.png)

**Comment by giorgiouboldi** [comment]
<img width="1680" alt="Screenshot 2022-05-10 at 02 41 38" src="https://user-images.githubusercontent.com/2106518/167586922-6fae45c7-aada-4421-aea9-59ab0c71118c.png">

**Comment by giorgiouboldi** [comment]
also for other story types: https://minett-stories.lu/en/story/but-we-women-also-have-to-fight-hard/explore

**Comment by skaffo** [comment]
@giorgiouboldi just fixed.
