### ISSUE TITLE
style links in articles

### ISSUE THREAD

**Issue by giorgiouboldi** [C2DH/minett-stories#94]
Lo farei colo "brick" - https://minett-stories.lu/en/story/brill

![Screenshot 2022-05-10 at 17 01 32](https://user-images.githubusercontent.com/2106518/167659976-06e82e3b-78d9-410f-95bf-fd4b55fd670d.png)

**Comment by skaffo** [comment]
@giorgiouboldi impostato colore brick per i link del long scroll.
